spring.application.name = workout-app

# DB config
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/workout
spring.datasource.username = postgres
spring.datasource.password = 123

# JPA configuration
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
# spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# View resolver
spring.mvc.view.prefix = /WEB-INF/views/
spring.mvc.view.suffix = .jsp

# GitHub OAuth2
spring.security.oauth2.client.registration.github.client-id = Ov23lihsYuSJWXhlLAei
spring.security.oauth2.client.registration.github.client-secret = c565392206154baf8f4625ca221f999502780115
spring.security.oauth2.client.registration.github.scope = read:user,user:email